name: AUR PKGBUILD from Cargo.toml
description: Action for generate and publish Aur PKGBUILD file from Cargo.toml
author: SergioRibera
branding:
  icon: 'package'
  color: 'orange'

inputs:
  # cargo-aur options
  proyect_path:
    description: The project path to generate PKGBUILD
    default: '.'
  musl:
    description: Build the binary as musl
    default: 'false'
  file:
    description: The path to the .tar.gz file to use
    default: ''
  output:
    description: Defines the folder from which the PKGBUILD file will be generated.
    default: out
  # AUR options
  package_name:
    description: The name in AUR of the package to release
    default: ${{ github.event.repository.name }}
  git_username:
    description: The username to use for the git commit
    default: 'AUR Release Action'
  git_email:
    description: The email to use for the git commit
    default: 'github-action-bot@no-reply.com'
  ssh_private_key:
    description: The private key to use for the git commit
    required: true
  publish:
    description: To publish or not to publish the package
    default: 'true'
  test_pkgbuild:
    description: Whether to try building and installing the package or not
    default: 'true'
  github_token:
    description: The GitHub token to use for the release
    required: true
  commit_message:
    description: The commit message to use for the git commit
    default: 'Bump %FILENAME% to %VERSION%'

outputs:
  file:
    description: The path to the generated .tar.gz file
  pkgbuild:
    description: The path to the generated PKGBUILD file

runs:
  using: docker
  image: Dockerfile
  args:
    # cargo-aur options
    - ${{ inputs.musl }}
    - ${{ inputs.file }}
    - ${{ inputs.output }}
    # AUR options
    - ${{ inputs.package_name }}
    - ${{ inputs.git_username }}
    - ${{ inputs.git_email }}
    - ${{ inputs.ssh_private_key }}
    - ${{ inputs.publish }}
    - ${{ inputs.test_pkgbuild }}
    - ${{ inputs.github_token }}
    - ${{ inputs.commit_message }}
